# Change these first
owner: gudasoft # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Cenite.com
    url: https://www.cenite.com
  - name: Gudasoft.com
    url: https://www.gudasoft.com/
  - name: Gudasoft Blog
    url: https://blog.gudasoft.com/
  - name: Data Listener
    url: https://data-listener.gudasoft.com/
  - name: Wannapik
    url: https://www.wannapik.com/
  - name: Club50plus
    url: https://club50plus.bg/
  - name: Kvartala
    url: https://www.kvartala.bg/
  - name: Advokatalexiev
    url: https://advokatalexiev.com/
  - name: Advokatalexiev
    url: https://advokatalexiev.com/
  - name: Belassitsa
    url: http://belassitsa.com/
  - name: Pancharevo-bg.com
    url: https://www.pancharevo-bg.com/robots.txt


assignees: # Users to assign downtime issues (optional)
  - gudata


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: upptime.js.org # Custom domain CNAME
  # name: Upptime # Status website title
  baseUrl: /upptime # where "repo" is your repository name
  name: Gudasoft Status Website
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  introTitle: "**Upptime** for Gudasoft Websites"
  introMessage: The uptimes and status pages for the webpages related to Gudasoft and their friends.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Gudasoft
      href: https://www.gudasoft.com
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
